# Rustfmt configuration for consistent code formatting

# Edition settings
edition = "2021"

# Line width and indentation
max_width = 100
tab_spaces = 4
hard_tabs = false

# Match formatting
match_block_trailing_comma = true

# Miscellaneous
use_field_init_shorthand = true
use_try_shorthand = true
